riff_mates/bands/urls.py
from django.urls import path

from bands import views

urlpatterns = [
    path('band/<int:band_id>/', views.band, name='band'),
    path('bands/', views.bands, name='bands'),
    path('musician/<int:musician_id>/', views.musician, name='musician'),
    path('musicians/', views.musicians, name='musicians'),
    path('venue/<int:venue_id>/', views.venue, name='venue'),
    path('venues/', views.venues, name='venues'),
    path('room/<int:room_id>', views.room, name='room'),
]

riff_mates/riff_mates/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', include('bands.urls')),
    path('credits/', home_views.credits, name="credits"),
    path('about/', home_views.about),
    path('version/', home_views.version),
    path('news/', home_views.news, name="news"),
    path('news_adv/', home_views.news_advanced, name="news_adv"),
]

riff_mates/bands/models.py
from django.db import models


class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth = models.DateField()

    def __str__(self) -> str:
        return f"Musician(id={self.id}, last_name={self.last_name})"

    class Meta:
        ordering = ["last_name", "first_name"]


class Venue(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self) -> str:
        return f"Venue(if={self.id}, name={self.name})"

    class Meta:
        ordering = ["name"]


class Room(models.Model):
    name = models.CharField(max_length=20)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"Room(id={self.id}, name={self.name})"

    class Meta:
        ordering = ["name"]
        unique_together = [["name", "venue"]]


class Band(models.Model):
    name = models.CharField(max_length=20)
    musicians = models.ManyToManyField(Musician)

    def __str__(self) -> str:
        return f"Band(id={self.id}, name={self.name})"

    class Meta:
        ordering = ["name"]

riff_mates/home/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)

riff_mates/bands/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from bands.models import Band
from bands.models import Musician
from bands.models import Room
from bands.models import Venue

DEFAULT_PER_PAGE = 2
MAXIMUM_PER_PAGE = 5


def musician(request, musician_id):
    data = {"musician": get_object_or_404(Musician, id=musician_id)}
    return render(request, "musician.html", data)


def band(request, band_id):
    data = {"band": get_object_or_404(Band, id=band_id)}
    return render(request, "band.html", data)


def venue(request, venue_id):
    data = {"venue": get_object_or_404(Venue, id=venue_id)}
    return render(request, "venue.html", data)


def room(request, room_id):
    data = {"room": get_object_or_404(Room, id=room_id)}
    return render(request, "room.html", data)


def get_items_per_page(request):
    per_page = int(request.GET.get("per_page", DEFAULT_PER_PAGE))

    if per_page < 1:
        per_page = DEFAULT_PER_PAGE
    elif per_page > 5:
        per_page = MAXIMUM_PER_PAGE

    return per_page


def get_page_num(request, paginator):
    page_num = int(request.GET.get("page", 1))

    if page_num < 1:
        page_num = 1
    elif page_num > paginator.num_pages:
        page_num = paginator.num_pages

    return page_num


def get_page(request, items):
    per_page = get_items_per_page(request)
    paginator = Paginator(items, per_page)
    page_num = get_page_num(request, paginator)
    return paginator.page(page_num)


def musicians(request):
    all_musicians = Musician.objects.all().order_by("last_name")
    page = get_page(request, all_musicians)
    return render(request, "musicians.html", {"musicians": page.object_list, "page": page})


def bands(request):
    all_bands = Band.objects.all().order_by("name")
    page = get_page(request, all_bands)
    return render(request, "bands.html", {"bands": page.object_list, "page": page})


def venues(request):
    all_venues = Venue.objects.all().order_by("name")
    page = get_page(request, all_venues)
    return render(request, "venues.html", {"venues": page.object_list, "page": page})

riff_mates/home/views.py
import datetime as dt

from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render


def credits(request):
    content = "Nicky\nYour Name"
    return HttpResponse(content, content_type="text/plain")


def about(request):
    content = "<div>'Django in Action' book project</div>"
    return HttpResponse(content, content_type="text/html")


def version(request):
    content = {"version": "2"}
    return JsonResponse(content)


def news(request):
    data = {
        "news": [
            "RiffMates now has a news page!",
            "RiffMates has its first web page",
        ]
    }
    return render(request, "news.html", data)


def news_advanced(request):
    data = {
        "news": [
            (dt.datetime.now(), "RiffMates now has a news page!"),
            (dt.datetime.now(), "RiffMates has its first web page"),
            (dt.datetime.now(), "RiffMates has advanced news page"),
        ]
    }
    return render(request, "news_adv.html", data)

riff_mates/templates/band.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Band Details
{% endblock title %}

{% block content %}
	<h1>{{ band.name }}</h1>
    <ul>
        {% for musician in band.musicians.all %}
        	<li><a href="{% url 'musician' musician.id %}">
                {{ musician.last_name }}, {{ musician.first_name }}
            </a></li>
        {% endfor %}
    </ul>
{% endblock content %}

riff_mates/templates/bands.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Band Listing	
{% endblock title %}

{% block content %}
	<h1>Bands</h1>
    
    <ul>
        {% for band in bands %}
        	<li><a href="{% url 'band' band.id %}">
                {{ band.name }}
            </a></li>
        {% empty %}
            <li><i>No bands in the database</i></li>
        {% endfor %}
    </ul>
    
    {% if page.has_other_pages %}
    	{% if page.has_previous %}
            <a href="{% url 'bands' %}?page={{ page.previous_page_number }}">Prev</a> &nbsp;&nbsp;&nbsp;
    	{% endif %} 
        {% if page.has_next %}
            <a href="{% url 'bands' %}?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    {% endif %} 
{% endblock content %}

riff_mates/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}RiffMates{% endblock title %}</title>
    
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

riff_mates/templates/musician.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Musician Details
{% endblock title %}

{% block content %}
	<h1>{{ musician.first_name }} {{ musician.last_name }}</h1>
    <p>Was born {{ musician.birth }}</p>
{% endblock content %}

riff_mates/templates/musicians.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Musician Listing	
{% endblock title %}

{% block content %}
	<h1>Musicians</h1>
    
    <ul>
        {% for musician in musicians %}
        	<li><a href="{% url 'musician' musician.id %}">
                {{ musician.last_name }}, {{ musician.first_name }}
            </a></li>
        {% empty %}
            <li><i>No musicians in the database</i></li>
        {% endfor %}
    </ul>
    
    {% if page.has_other_pages %}
    	{% if page.has_previous %}
            <a href="{% url 'musicians' %}?page={{ page.previous_page_number }}">Prev</a> &nbsp;&nbsp;&nbsp;
    	{% endif %} 
        {% if page.has_next %}
            <a href="{% url 'musicians' %}?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    {% endif %} 
{% endblock content %}

riff_mates/templates/news.html
{% extends 'base.html' %}

{% block title %}
	{{ block.super }}: News
{% endblock title %}

{% block content %}
	<h1>RiffMates News</h1>
    <ul>
        {% for item in news %}
        	<li>{{ item }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

riff_mates/templates/news_adv.html
{% extends 'base.html' %}

{% block title %}
	{{ block.super }}: News
{% endblock title %}

{% block content %}
	<h1>RiffMates News</h1>
    
    <table>
    {% for item in news %}
    	<tr style="background-color: {% cycle '#F0F0F0' '#E8E8E8' %}">
            <td>{{ item.0 | date:"d:m:Y" }}</td>
            <td>{{ item.1 }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock content %}

riff_mates/templates/room.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Room Details
{% endblock title %}

{% block content %}
	<h1>{{ room.name }}</h1>
{% endblock content %}

riff_mates/templates/venue.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Venue Details
{% endblock title %}

{% block content %}
	<h1>{{ venue.name }}</h1>
    <ul>
        {% for room in venue.room_set.all %}
        	<li><a href="{% url 'room' room.id %}">
                {{ room.name }}
            </a></li>
        {% endfor %}
    </ul>
{% endblock content %}

riff_mates/templates/venues.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}: Venue Listing	
{% endblock title %}

{% block content %}
	<h1>Bands</h1>
    
    <ul>
        {% for venue in venues %}
        	<li><a href="{% url 'venue' venue.id %}">
                {{ venue.name }}
            </a></li>
        {% empty %}
            <li><i>No venues in the database</i></li>
        {% endfor %}
    </ul>
    
    {% if page.has_other_pages %}
    	{% if page.has_previous %}
            <a href="{% url 'bands' %}?page={{ page.previous_page_number }}&per_page={{ per_page }}">Prev</a> &nbsp;&nbsp;&nbsp;
    	{% endif %} 
        {% if page.has_next %}
            <a href="{% url 'bands' %}?page={{ page.next_page_number }}&per_page={{ per_page }}">Next</a>
        {% endif %}
    {% endif %} 
{% endblock content %}